# Use uma imagem base do Python
FROM python:3.10-slim AS base

# Defina o diretório de trabalho dentro do container
WORKDIR /app

# Copie o arquivo de requisitos e instale as dependências
COPY requirements.txt .

# Atualize o pip e instale as dependências
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copie o código da aplicação e o modelo salvo para o container
COPY . .

# Expor as portas da API e do servidor de métricas
EXPOSE 5000
EXPOSE 8000

# Comando para iniciar a API
CMD ["python", "app.py"]
